language: java
sudo: false
jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk10
  - openjdk11
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
script:
  - ./gradlew clean build coverage
notifications:
  email: false
